# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgmanager',
            name='cell',
            field=models.CharField(max_length=14),
        ),
    ]
