# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
