# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0002_auto_20181110_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField(max_length=250)),
            ],
            options={
                'db_table': 'pg',
            },
        ),
        migrations.AlterField(
            model_name='pgmanager',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='pg',
            name='pgmanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgmanager.PGManager'),
        ),
    ]
