# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0003_auto_20181110_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
