# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pgmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0005_auto_20181110_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('AC', 'AC ROOM'), ('NAC', 'Non AC ROOM')], max_length=3)),
                ('cost', models.IntegerField()),
                ('strength', models.IntegerField(blank=True, default=1)),
                ('status', models.BooleanField(default=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgmanager.PG')),
            ],
        ),
        migrations.AlterField(
            model_name='pgmanager',
            name='cell',
            field=models.CharField(max_length=14, unique=True, validators=[pgmanager.models.cellvalidation]),
        ),
        migrations.AlterField(
            model_name='pgmanager',
            name='name',
            field=models.CharField(max_length=60, validators=[pgmanager.models.namevalidation]),
        ),
    ]
