# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0006_auto_20181111_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='pgmanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pgmanager.PGManager'),
        ),
        migrations.AlterField(
            model_name='room',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pgmanager.PG'),
        ),
    ]
